-- =====================================================================
-- Lookup tables, standardized extraction
-- Database : PSSM2025 (dbo)
-- Replaces : INFOWARE_L_CIP_4DIGITS_CIP2021.sql, INFOWARE_L_CIP_6DIGITS_CIP2021.sql
-- Standard : see refactored/README.md
-- =====================================================================
SELECT
    LCP4_CD              AS LCP4_CD,
    LCP4_DIGITS_NAME     AS LCP4_DIGITS_NAME,
    LCIP4_CD_WITH_PERIOD AS LCP4_CD_WITH_PERIOD
FROM dbo.INFOWARE_L_CIP_4DIGITS_CIP2021

SELECT
    LCP6_CD              AS LCP6_CD,
    LCP6_DIGITS_NAME     AS LCP6_DIGITS_NAME,
    LCIP_CD_WITH_PERIOD  AS LCP6_CD_WITH_PERIOD,
    LCIP_LCP4_CD         AS LCP4_CD,
    LCIP_LCP2_CD         AS LCP2_CD,
    LCIP_LCIPPC_CD       AS LCIP_LCIPPC_CD,
    LCIP_LCIPPC_NAME     AS LCIP_LCIPPC_NAME,
    LCIP_STATSCAN_STEM_CD AS STATSCAN_STEM_CD,
    LCIP_STATSCAN_STEM_GROUP AS STATSCAN_STEM_GROUP
FROM dbo.INFOWARE_L_CIP_6DIGITS_CIP2021

SELECT
    PRGM_ID                    AS PRGM_ID,
    PRGM_FIRST_SEEN_SUBM_CD    AS PRGM_FIRST_SEEN_SUBM_CD,
    PRGM_INST_CD               AS PRGM_INST_CD,
    PRGM_INST_PROGRAM_NAME     AS PRGM_INST_PROGRAM_NAME,
    PRGM_INST_PROGRAM_NAME_CLEANED AS PRGM_INST_PROGRAM_NAME_CLEANED,
    DASHBOARD_CPC_NAME         AS DASHBOARD_CPC_NAME,
    PRGM_LCPC_CD               AS PRGM_LCPC_CD,
    APP_TYPE                   AS APP_TYPE,
    PRGM_TTRAIN_FLAG           AS PRGM_TTRAIN_FLAG,
    PRGM_TRADE_PROGRAM_CODE    AS PRGM_TRADE_PROGRAM_CODE,
    PRGM_TRADE_PROGRAM_GROUPING AS PRGM_TRADE_PROGRAM_GROUPING,
    PRGM_CREDENTIAL            AS PRGM_CREDENTIAL,
    OLD_PRGMID               AS OLD_PRGMID,
    LCIP_CD_CIP2021            AS LCIP_CD_CIP2021,
    LCIP_NAME_CIP2021          AS LCIP_NAME_CIP2021,
    LCIP_LCIPPC_CD_2021        AS LCIP_LCIPPC_CD_2021,
    LCIP_LCIPPC_NAME_2021      AS LCIP_LCIPPC_NAME_2021,
    DACSO_PRGM_ID              AS DACSO_PRGM_ID
FROM dbo.INFOWARE_PROGRAMS

SELECT
    SURVEY             AS SURVEY,
    YEAR_CODE          AS YEAR_CODE,
    SUBM_CD            AS SUBM_CD,
    SURVEY_YEAR        AS SURVEY_YEAR,
    AWARD_SCHOOL_YEAR  AS AWARD_SCHOOL_YEAR,
    PROJECTION_YEAR    AS PROJECTION_YEAR
FROM dbo.t_year_survey_year_r
