qry_make_tmp_table_Age_step1 <- "
SELECT SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID, SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD, CO_COHORT_SAMPLE_2018.BTHDT, CO_COHORT_SAMPLE_2018.ENDDT, 
SURV_COHORT_COLLECTION_INFO.COCI_AGE_AT_SURVEY
FROM CO_COHORT_SAMPLE_2018 INNER JOIN SURV_COHORT_COLLECTION_INFO ON CO_COHORT_SAMPLE_2018.STQU_ID = SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID
WHERE (((SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD)='C_Outc18'))
UNION ALL
SELECT SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID, SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD, CO_COHORT_SAMPLE_2019.BTHDT, CO_COHORT_SAMPLE_2019.ENDDT, 
SURV_COHORT_COLLECTION_INFO.COCI_AGE_AT_SURVEY
FROM CO_COHORT_SAMPLE_2019 INNER JOIN SURV_COHORT_COLLECTION_INFO ON CO_COHORT_SAMPLE_2019.STQU_ID = SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID
WHERE (((SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD)='C_Outc19'))
UNION ALL
SELECT SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID, SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD, CO_COHORT_SAMPLE_2020.BTHDT, CO_COHORT_SAMPLE_2020.ENDDT, 
SURV_COHORT_COLLECTION_INFO.COCI_AGE_AT_SURVEY
FROM CO_COHORT_SAMPLE_2020 INNER JOIN SURV_COHORT_COLLECTION_INFO ON CO_COHORT_SAMPLE_2020.STQU_ID = SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID
WHERE (((SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD)='C_Outc20'))
UNION ALL
SELECT SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID, SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD, CO_COHORT_SAMPLE_2021.BTHDT, CO_COHORT_SAMPLE_2021.ENDDT, 
SURV_COHORT_COLLECTION_INFO.COCI_AGE_AT_SURVEY
FROM CO_COHORT_SAMPLE_2021 INNER JOIN SURV_COHORT_COLLECTION_INFO ON CO_COHORT_SAMPLE_2021.STQU_ID = SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID
WHERE (((SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD)='C_Outc21'))
UNION ALL
SELECT SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID, SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD, CO_COHORT_SAMPLE_2022.BTHDT, CO_COHORT_SAMPLE_2022.ENDDT, 
SURV_COHORT_COLLECTION_INFO.COCI_AGE_AT_SURVEY
FROM CO_COHORT_SAMPLE_2022 INNER JOIN SURV_COHORT_COLLECTION_INFO ON CO_COHORT_SAMPLE_2022.STQU_ID = SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID
WHERE (((SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD)='C_Outc22'))
UNION ALL
SELECT SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID, SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD, CO_COHORT_SAMPLE_2023.BTHDT, CO_COHORT_SAMPLE_2023.ENDDT, 
SURV_COHORT_COLLECTION_INFO.COCI_AGE_AT_SURVEY
FROM CO_COHORT_SAMPLE_2023 INNER JOIN SURV_COHORT_COLLECTION_INFO ON CO_COHORT_SAMPLE_2023.STQU_ID = SURV_COHORT_COLLECTION_INFO.COCI_STQU_ID
WHERE (((SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD)='C_Outc23'))"