SELECT
    COCI_STQU_ID,
    COCI_SUBM_CD,
    TPID_DATE_OF_BIRTH AS BTHDT,
    COSC_ENRL_END_DATE AS ENDDT,
    COCI_AGE_AT_SURVEY
FROM
    SURV_COHORT_COLLECTION_INFO
    WHERE SURV_COHORT_COLLECTION_INFO.COCI_SUBM_CD IN ('C_Outc21', 'C_Outc22', 'C_Outc23', 'C_Outc24', 'C_Outc25')
ORDER BY
    COSC_TTRAIN, COCI_STQU_ID;