# Copyright 2024 Province of British Columbia
# Licensed under the Apache License, Version 2.0
#
# Purpose
# -------
# Direct dplyr/dbplyr translation of the SQL logic from 02a-appso-programs.
# This is intentionally a close translation of the SQL steps, not a refactor.
#
# Notes
# -----
# - This script assumes the source tables already exist in the database.
# - The objects below are lazy dbplyr tables unless collect() or compute() is used.
# - Where SQL used UPDATE statements, this translation uses sequential mutate() /
#   join() steps to create the same result set.
# - Some remote databases need compute() between steps for performance or to avoid
#   repeating large subqueries. Those calls are left commented for now.
#
# TODO markers for later refactor
# -----------------------------
# TODO: Break the pipeline into named functions so each transformation step can be tested separately.
# TODO: Add a match_method column that records how each CIP was derived.
# TODO: Review remote SQL generated by dbplyr and add compute() at the right choke points.
# TODO: Replace repeated fallback join patterns with reusable helper functions.
# TODO: Move hard-coded business rules and output table names into config or lookup tables.

library(dplyr)
library(dbplyr)
library(DBI)
library(odbc)
library(config)

# ---- Configure database connection -------------------------------------------
db_config <- config::get("decimal")
my_schema <- config::get("myschema")

con <- dbConnect(
  odbc(),
  Driver = db_config$driver,
  Server = db_config$server,
  Database = db_config$database,
  Trusted_Connection = "True"
)

# ---- Reference source tables -------------------------------------------------
# Adjust schema/table resolution if your environment stores these elsewhere.
# TODO: Wrap table access in a helper that validates existence and returns a clearer error.

credential_non_dup <- tbl(con, in_schema(my_schema, "Credential_Non_Dup")) %>%
  rename_with(toupper)
colnames(credential_non_dup)
infoware_l_cip_2digits_cip2016 <- tbl(
  con,
  in_schema(my_schema, "INFOWARE_L_CIP_2DIGITS_CIP2016")
)
infoware_l_cip_4digits_cip2016 <- tbl(
  con,
  in_schema(my_schema, "INFOWARE_L_CIP_4DIGITS_CIP2016")
)
infoware_l_cip_6digits_cip2016 <- tbl(
  con,
  in_schema(my_schema, "INFOWARE_L_CIP_6DIGITS_CIP2016")
)

# ---- 1) SQL: create Credential_Non_Dup_STP_APPSO_Cleaning -------------------
credential_non_dup_stp_appso_cleaning <- credential_non_dup %>%
  filter(OUTCOMES_CRED == "APPSO") %>%
  count(PSI_CREDENTIAL_CIP, OUTCOMES_CRED, name = "Expr1")

# ---- 2) SQL: alter table + update original CIP -------------------------------
# Placeholder for records finalized through manual review in Part 3C
# The reason: dbplyr translates NA_character_ → SQL NULL (no type). SQL Server then defaults untyped NULL to int. Using sql("CAST(NULL AS VARCHAR(255))") forces the database to treat it as a character column.

credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  mutate(
    STP_CIP_CODE_4 = sql("CAST(NULL AS VARCHAR(255))"),
    STP_CIP_CODE_4_NAME = sql("CAST(NULL AS VARCHAR(255))"),
    STP_CIP_CODE_2 = sql("CAST(NULL AS VARCHAR(255))"),
    STP_CIP_CODE_2_NAME = sql("CAST(NULL AS VARCHAR(255))"),
    PSI_CREDENTIAL_CIP_orig = PSI_CREDENTIAL_CIP
  )

# ---- 3) SQL: clean malformed CIP values --------------------------------------
# Step 3a equivalent: append trailing zero for 6-character values whose first
# two characters do not contain a period.
# TODO: Replace the inline CIP cleanup logic with a single tested standardization helper.
credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  mutate(
    PSI_CREDENTIAL_CIP = case_when(
      nchar(PSI_CREDENTIAL_CIP) == 6 &
        substr(PSI_CREDENTIAL_CIP, 2, 2) != "\\." ~
        paste0(PSI_CREDENTIAL_CIP, "0"),
      TRUE ~ PSI_CREDENTIAL_CIP
    )
  )

# Step 3b equivalent: prepend leading zero for any value still length 6.
credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  mutate(
    PSI_CREDENTIAL_CIP = case_when(
      nchar(PSI_CREDENTIAL_CIP) == 6 ~ paste0("0", PSI_CREDENTIAL_CIP),
      TRUE ~ PSI_CREDENTIAL_CIP
    )
  )

# ---- 4) SQL Step1_a: exact match to INFOWARE 6-digit CIP table --------------
exact_match_6 <- infoware_l_cip_6digits_cip2016 %>%
  select(
    LCIP_CD_WITH_PERIOD,
    exact_STP_CIP_CODE_4 = LCIP_LCP4_CD,
    exact_STP_CIP_CODE_2 = LCIP_LCP2_CD
  )

credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  left_join(
    exact_match_6,
    by = c("PSI_CREDENTIAL_CIP" = "LCIP_CD_WITH_PERIOD")
  ) %>%
  mutate(
    STP_CIP_CODE_4 = coalesce(exact_STP_CIP_CODE_4, STP_CIP_CODE_4),
    STP_CIP_CODE_2 = coalesce(exact_STP_CIP_CODE_2, STP_CIP_CODE_2)
  ) %>%
  select(-exact_STP_CIP_CODE_4, -exact_STP_CIP_CODE_2)

# ---- 5) SQL Step1_b: fallback match on first 5 characters --------------------
# TODO: Confirm this does not create duplicate matches on databases where the
#       5-character prefix is not unique in the reference table.
fallback_match_5 <- credential_non_dup_stp_appso_cleaning %>%
  filter(is.na(STP_CIP_CODE_4)) %>%
  mutate(join_key_5 = substr(PSI_CREDENTIAL_CIP, 1, 5)) %>%
  select(PSI_CREDENTIAL_CIP, OUTCOMES_CRED, join_key_5)

infoware_join_5 <- infoware_l_cip_6digits_cip2016 %>%
  mutate(join_key_5 = substr(LCIP_CD_WITH_PERIOD, 1, 5)) %>%
  select(
    join_key_5,
    fallback_STP_CIP_CODE_4 = LCIP_LCP4_CD,
    fallback_STP_CIP_CODE_2 = LCIP_LCP2_CD
  )

fallback_updates_5 <- fallback_match_5 %>%
  inner_join(infoware_join_5, by = "join_key_5") %>%
  select(
    PSI_CREDENTIAL_CIP,
    OUTCOMES_CRED,
    fallback_STP_CIP_CODE_4,
    fallback_STP_CIP_CODE_2
  )

credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  left_join(
    fallback_updates_5,
    by = c("PSI_CREDENTIAL_CIP", "OUTCOMES_CRED")
  ) %>%
  mutate(
    STP_CIP_CODE_4 = coalesce(STP_CIP_CODE_4, fallback_STP_CIP_CODE_4),
    STP_CIP_CODE_2 = coalesce(STP_CIP_CODE_2, fallback_STP_CIP_CODE_2)
  ) %>%
  select(-fallback_STP_CIP_CODE_4, -fallback_STP_CIP_CODE_2)

# ---- 6) SQL Step1_c: general program rule (.00 -> 01) ------------------------
# TODO: Move the hard-coded prefix vector into a maintained lookup table or config object.
general_program_prefixes <- c(
  "11.00",
  "13.00",
  "14.00",
  "19.00",
  "23.00",
  "24.00",
  "26.00",
  "40.00",
  "42.00",
  "45.00",
  "50.00",
  "52.00",
  "55.00"
)

credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  mutate(
    # TODO: Add match_method updates here once refactor starts.
    STP_CIP_CODE_4 = case_when(
      is.na(STP_CIP_CODE_4) &
        substr(PSI_CREDENTIAL_CIP, 1, 5) %in% general_program_prefixes ~
        paste0(substr(PSI_CREDENTIAL_CIP, 1, 2), "01"),
      TRUE ~ STP_CIP_CODE_4
    )
  )

# ---- 7) SQL Step1_d: fallback 2-digit match on first 2 characters ------------
fallback_match_2 <- credential_non_dup_stp_appso_cleaning %>%
  filter(is.na(STP_CIP_CODE_2)) %>%
  mutate(join_key_2 = substr(PSI_CREDENTIAL_CIP, 1, 2)) %>%
  select(PSI_CREDENTIAL_CIP, OUTCOMES_CRED, join_key_2)

infoware_join_2 <- infoware_l_cip_6digits_cip2016 %>%
  mutate(join_key_2 = substr(LCIP_CD_WITH_PERIOD, 1, 2)) %>%
  select(join_key_2, fallback_STP_CIP_CODE_2 = LCIP_LCP2_CD)

fallback_updates_2 <- fallback_match_2 %>%
  inner_join(infoware_join_2, by = "join_key_2") %>%
  select(PSI_CREDENTIAL_CIP, OUTCOMES_CRED, fallback_STP_CIP_CODE_2)

credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  left_join(
    fallback_updates_2,
    by = c("PSI_CREDENTIAL_CIP", "OUTCOMES_CRED")
  ) %>%
  mutate(
    STP_CIP_CODE_2 = coalesce(STP_CIP_CODE_2, fallback_STP_CIP_CODE_2)
  ) %>%
  select(-fallback_STP_CIP_CODE_2)

# ---- 8) SQL Step2: add 4-digit CIP names -------------------------------------
credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  left_join(
    infoware_l_cip_4digits_cip2016 %>%
      select(
        STP_CIP_CODE_4 = LCP4_CD,
        STP_CIP_CODE_4_NAME_lookup = LCP4_CIP_4DIGITS_NAME
      ),
    by = "STP_CIP_CODE_4"
  ) %>%
  mutate(
    STP_CIP_CODE_4_NAME = coalesce(
      STP_CIP_CODE_4_NAME_lookup,
      STP_CIP_CODE_4_NAME
    )
  ) %>%
  select(-STP_CIP_CODE_4_NAME_lookup)

# ---- 9) SQL Step3: add 2-digit CIP names -------------------------------------
credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  left_join(
    infoware_l_cip_2digits_cip2016 %>%
      select(
        STP_CIP_CODE_2 = LCP2_CD,
        STP_CIP_CODE_2_NAME_lookup = LCP2_DIGITS_NAME
      ),
    by = "STP_CIP_CODE_2"
  ) %>%
  mutate(
    STP_CIP_CODE_2_NAME = coalesce(
      STP_CIP_CODE_2_NAME_lookup,
      STP_CIP_CODE_2_NAME
    )
  ) %>%
  select(-STP_CIP_CODE_2_NAME_lookup)

# ---- 10) SQL Step4: mark missing 4-digit names as invalid --------------------
credential_non_dup_stp_appso_cleaning <- credential_non_dup_stp_appso_cleaning %>%
  mutate(
    STP_CIP_CODE_4_NAME = coalesce(STP_CIP_CODE_4_NAME, "Invalid 4-digit CIP")
  )

# ---- 11) SQL: create Credential_Non_Dup_APPSO_IDs ----------------------------
# TODO: Validate join cardinality before materializing the final output.
credential_non_dup_appso_ids <- credential_non_dup %>%
  select(
    ID,
    PSI_CODE,
    PSI_PROGRAM_CODE,
    PSI_CREDENTIAL_PROGRAM_DESCRIPTION,
    PSI_CREDENTIAL_CIP,
    PSI_AWARD_SCHOOL_YEAR,
    OUTCOMES_CRED,
  ) |>
  filter(OUTCOMES_CRED == "APPSO") %>%
  inner_join(
    credential_non_dup_stp_appso_cleaning,
    by = c(
      "PSI_CREDENTIAL_CIP" = "PSI_CREDENTIAL_CIP_orig",
      "OUTCOMES_CRED" = "OUTCOMES_CRED"
    )
  ) %>%
  transmute(
    ID,
    PSI_CODE,
    PSI_PROGRAM_CODE,
    PSI_CREDENTIAL_PROGRAM_DESCRIPTION,
    PSI_CREDENTIAL_CIP,
    PSI_AWARD_SCHOOL_YEAR,
    OUTCOMES_CRED,
    FINAL_CIP_CODE_4 = STP_CIP_CODE_4,
    FINAL_CIP_CODE_4_NAME = STP_CIP_CODE_4_NAME,
    FINAL_CIP_CODE_2 = STP_CIP_CODE_2,
    FINAL_CIP_CODE_2_NAME = STP_CIP_CODE_2_NAME
  )

# ---- 12) SQL: replace '(Unspecified)' with NULL ------------------------------
credential_non_dup_appso_ids <- credential_non_dup_appso_ids %>%
  mutate(
    PSI_PROGRAM_CODE = na_if(PSI_PROGRAM_CODE, "(Unspecified)")
  )

# write the table back to the database using computing function

# ---- Optional materialization -------------------------------------------------
# Uncomment if you want to persist the translated result back to the database.
# TODO: In refactor, centralize write targets and table lifecycle rules in one place.
# compute() writes the lazy query to a physical table.
#
credential_non_dup_appso_ids %>%
  compute(
    name = in_schema(my_schema, "Credential_Non_Dup_APPSO_IDs"),
    temporary = FALSE
  )

# credential_non_dup_stp_appso_cleaning %>%
#   compute(
#     name = in_schema(my_schema, "Credential_Non_Dup_STP_APPSO_Cleaning"),
#     temporary = FALSE
#   )

# ---- Disconnect ---------------------------------------------------------------
dbDisconnect(con)
