# Notes: watch for Age_Grouping variable, documentation mentions having removed it from earlier queries and linked later.  not sure what this means.
# also, need to update T-Year_Survey_Year as is a dependency in DACSO_Q005_DACSO_DATA_Part_1b2_Cohort_Recoded.  The pattern to update is obvious from prior
# year's entries, but some rationale would be helpful.

library(tidyverse)
library(RODBC)
library(config)
library(DBI)
library(RJDBC)

# ---- Configure LAN and file paths ----
db_config <- config::get("decimal")
lan <- config::get("lan")
my_schema <- config::get("myschema")

# ---- Connection to database ----
db_config <- config::get("decimal")
decimal_con <- dbConnect(odbc::odbc(),
                         Driver = db_config$driver,
                         Server = db_config$server,
                         Database = db_config$database,
                         Trusted_Connection = "True")

# ---- Read raw data ----
source(glue::glue("{lan}/development/sql/gh-source/02b-pssm-cohorts/02b-pssm-cohorts-new-labour-supply.R"))
dbExistsTable(decimal_con, SQL(glue::glue('"{my_schema}".""')))
dbExistsTable(decimal_con, SQL(glue::glue('"{my_schema}".""')))
dbExistsTable(decimal_con, SQL(glue::glue('"{my_schema}".""')))
dbExistsTable(decimal_con, SQL(glue::glue('"{my_schema}".""')))

# ---- Execute SQL ----
dbExecute(decimal_con, DACSO_Q008_Z01_Base_OCC)
dbExecute(decimal_con, DACSO_Q008_Z02a_Base)
dbExecute(decimal_con, DACSO_Q008_Z02b_Respondents)
dbExecute(decimal_con, DACSO_Q008_Z02b_Respondents_NOC_9999)
dbExecute(decimal_con, DACSO_Q008_Z02b_Respondents_Union)
dbExecute(decimal_con, DACSO_Q008_Z02c_Weight)
dbExecute(decimal_con, DACSO_Q008_Z03_Weight_Total)
dbExecute(decimal_con, DACSO_Q008_Z04_Weight_Adj_Fac)
dbExecute(decimal_con, DACSO_Q008_Z05_Weight_OCC)
dbExecute(decimal_con, DACSO_Q008_Z05b_Finding_NLS2_Missing)
dbExecute(decimal_con, DACSO_Q008_Z05b_NOC4D_NLS_XTab)
dbExecute(decimal_con, DACSO_Q008_Z05b_Weight_Comparison)
dbExecute(decimal_con, DACSO_Q008_Z08_Weight_OCC_Update)
dbExecute(decimal_con, DACSO_Q008_Z09_Check_Weights)
dbExecute(decimal_con, DACSO_Q009_Weight_Occs)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_2D)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_2D_BC)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_2D_BC_No_TT)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_2D_No_TT)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_Total_2D)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_Total_2D_BC)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_Total_2D_BC_No_TT)
dbExecute(decimal_con, DACSO_Q009_Weighted_Occs_Total_2D_No_TT)
dbExecute(decimal_con, DACSO_Q009b_Weighted_Occs)
dbExecute(decimal_con, DACSO_Q009b_Weighted_Occs_No_TT)
dbExecute(decimal_con, DACSO_Q009b_Weighted_Occs_Total)
dbExecute(decimal_con, DACSO_Q009b_Weighted_Occs_Total_No_TT)
dbExecute(decimal_con, DACSO_Q010_Weighted_Occs_Dist)
dbExecute(decimal_con, DACSO_Q010_Weighted_Occs_Dist_2D)
dbExecute(decimal_con, DACSO_Q010_Weighted_Occs_Dist_2D_BC)
dbExecute(decimal_con, DACSO_Q010_Weighted_Occs_Dist_2D_BC_No_TT)
dbExecute(decimal_con, DACSO_Q010_Weighted_Occs_Dist_2D_No_TT)
dbExecute(decimal_con, DACSO_Q010_Weighted_Occs_Dist_No_TT)
dbExecute(decimal_con, DACSO_Q010a0_Delete_Occupational_Distribution)
dbExecute(decimal_con, DACSO_Q010a0_Delete_Occupational_Distribution_No_TT)
dbExecute(decimal_con, DACSO_Q010a0_Delete_Occupational_Distribution_No_TT_QI)
dbExecute(decimal_con, DACSO_Q010a0_Delete_Occupational_Distribution_QI)
dbExecute(decimal_con, DACSO_Q010a1_Append_Occupational_Distribution)
dbExecute(decimal_con, DACSO_Q010a1_Append_Occupational_Distribution_No_TT)
dbExecute(decimal_con, DACSO_Q010b0_Delete_Occupational_Distribution_LCP2)
dbExecute(decimal_con, DACSO_Q010b0_Delete_Occupational_Distribution_LCP2_No_TT)
dbExecute(decimal_con, DACSO_Q010b0_Delete_Occupational_Distribution_LCP2_No_TT_QI)
dbExecute(decimal_con, DACSO_Q010b0_Delete_Occupational_Distribution_LCP2_QI)
dbExecute(decimal_con, DACSO_Q010b1_Append_Occupational_Distribution_LCP2)
dbExecute(decimal_con, DACSO_Q010b1_Append_Occupational_Distribution_LCP2_No_TT)
dbExecute(decimal_con, DACSO_Q010c0_Delete_Occupational_Distribution_LCP2_BC)
dbExecute(decimal_con, DACSO_Q010c0_Delete_Occupational_Distribution_LCP2_BC_No_TT)
dbExecute(decimal_con, DACSO_Q010c0_Delete_Occupational_Distribution_LCP2_BC_No_TT_QI)
dbExecute(decimal_con, DACSO_Q010c0_Delete_Occupational_Distribution_LCP2_BC_QI)
dbExecute(decimal_con, DACSO_Q010c1_Append_Occupational_Distribution_LCP2_BC)
dbExecute(decimal_con, DACSO_Q010c1_Append_Occupational_Distribution_LCP2_BC_No_TT)
dbExecute(decimal_con, DACSO_Q010d1_Delete_PDEG_CIP_Cluster_07_Law_New_Labour_Supply)
dbExecute(decimal_con, DACSO_Q010d1_Delete_PDEG_CIP_Cluster_07_Law_New_Labour_Supply_QI)
dbExecute(decimal_con, DACSO_Q010d2_NLS_PDEG_07_Count)
dbExecute(decimal_con, DACSO_Q010d3_NLS_PDEG_07_Subtotal)
dbExecute(decimal_con, DACSO_Q010d4_NLS_PDEG_07_Total)
dbExecute(decimal_con, DACSO_Q010d5_NLS_PDEG_07_Weighted_New_Labour_Supply)
dbExecute(decimal_con, DACSO_Q010d6_Append_NLS_PDEG_07_New_Labour_Supply)
dbExecute(decimal_con, DACSO_Q010e1_Delete_PDEG_CIP_Cluster_07_Law_Occupation_Dist)
dbExecute(decimal_con, DACSO_Q010e1_Delete_PDEG_CIP_Cluster_07_Law_Occupation_Dist_QI)
dbExecute(decimal_con, DACSO_Q010e2_Weighted_Occs_PDEG_07)
dbExecute(decimal_con, DACSO_Q010e3_Weighted_Occs_Total_PDEG_07)
dbExecute(decimal_con, DACSO_Q010e4_Weighted_Occs_Dist_PDEG_07)
dbExecute(decimal_con, DACSO_Q010e5_Append_Occupational_Distribution_PDEG_07)
dbExecute(decimal_con, DACSO_Q99A_ENDDT_IMPUTED)
dbExecute(decimal_con, DACSO_qry99_Suppression_Public_Release_NOC)

# ---- Clean Up ----
dbDisconnect(decimal_con)
